# Generated by Django 4.2.23 on 2026-07-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Duyuru Başlığı')),
                ('content', models.TextField(verbose_name='Duyuru İçeriği')),
                ('category', models.CharField(choices=[('görev', 'Yeni Görev Tanımı'), ('doküman', 'Güncellenen Dokümanlar'), ('yeni_doküman', 'Yeni Yayınlanan Dokümanlar'), ('genel', 'Genel Duyuru')], default='genel', max_length=50, verbose_name='Kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='İlgili Bağlantı')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='İstatistik Anahtarı')),
                ('label', models.CharField(max_length=100, verbose_name='Başlık')),
                ('count', models.IntegerField(default=0, verbose_name='Toplam Sayı')),
                ('new_count', models.IntegerField(default=0, verbose_name='Yeni Eklenen (Bu Ay)')),
                ('icon', models.CharField(default='fa-user', max_length=50, verbose_name='FontAwesome İkonu')),
                ('color_class', models.CharField(default='icon-blue', max_length=50, verbose_name='Renk Sınıfı')),
            ],
            options={
                'verbose_name': 'Sistem İstatistiği',
                'verbose_name_plural': 'Sistem İstatistikleri',
            },
        ),
    ]
