# Generated by Django 4.2.23 on 2026-07-06 06:06

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=feedback.models.generate_tracking_code, max_length=15, unique=True, verbose_name='Takip Kodu')),
                ('feedback_type', models.CharField(choices=[('öneri', 'Öneri / Tavsiye'), ('şikayet', 'Şikayet / Memnuniyetsizlik'), ('takdir', 'Takdir / Teşekkür'), ('diğer', 'Diğer Kalite Bildirimi')], default='öneri', max_length=20, verbose_name='Bildirim Türü')),
                ('user_type', models.CharField(choices=[('öğrenci', 'Öğrenci'), ('akademik', 'Akademik Personel'), ('idari', 'İdari Personel'), ('dış', 'Dış Paydaş / Ziyaretçi')], default='öğrenci', max_length=20, verbose_name='Paydaş Türü')),
                ('unit', models.CharField(default='Avrasya Üniversitesi Genel', max_length=150, verbose_name='İlgili Birim / Fakülte')),
                ('name_surname', models.CharField(blank=True, default='Anonim Paydaş', max_length=100, null=True, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Bildirim Detayı / Mesaj')),
                ('status', models.CharField(choices=[('beklemede', 'Beklemede / İçe aktarıldı'), ('islemde', 'Değerlendirme Aşamasında'), ('cozuldu', 'Çözüldü / Sonuçlandı')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Birim / Kalite Koordinatörlüğü Cevabı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Geri Bildirim',
                'verbose_name_plural': 'Geri Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
