# Generated by Django 4.2.23 on 2026-07-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Örn: PP.2.3.GT.0583', max_length=50, unique=True, verbose_name='Görev Tanım Kodu')),
                ('title', models.CharField(max_length=200, verbose_name='Görev Unvanı')),
                ('department', models.CharField(max_length=150, verbose_name='Bağlı Olduğu Birim')),
                ('responsibilities', models.TextField(verbose_name='Temel Görev ve Sorumluluklar')),
                ('qualifications', models.TextField(verbose_name='Aranan Nitelikler')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Görev Tanımı',
                'verbose_name_plural': 'Görev Tanımları',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Örn: SR.01', max_length=50, unique=True, verbose_name='Süreç Kodu')),
                ('name', models.CharField(max_length=200, verbose_name='Süreç Adı')),
                ('owner', models.CharField(default='Rektör Yardımcısı', max_length=150, verbose_name='Süreç Sorumlusu')),
                ('purpose', models.TextField(verbose_name='Süreç Amacı')),
                ('inputs', models.TextField(help_text='Virgülle veya satırla ayırabilirsiniz', verbose_name='Süreç Girdileri')),
                ('outputs', models.TextField(verbose_name='Süreç Çıktıları')),
                ('kpi', models.TextField(verbose_name='Performans Göstergeleri (KPI)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Süreç Kartı',
                'verbose_name_plural': 'Süreç Kartları',
                'ordering': ['code'],
            },
        ),
    ]
