# Generated by Django 4.2.23 on 2026-07-06 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('code', models.CharField(help_text='Örn: FR, PR, TAL', max_length=20, unique=True, verbose_name='Kategori Kodu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('icon', models.CharField(default='fa-folder-open', max_length=50, verbose_name='İkon')),
            ],
            options={
                'verbose_name': 'Doküman Kategorisi',
                'verbose_name_plural': 'Doküman Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Örn: PP.1.2.FR.0033', max_length=50, unique=True, verbose_name='Doküman Kodu')),
                ('title', models.CharField(max_length=255, verbose_name='Doküman Adı')),
                ('unit', models.CharField(default='Avrasya Rektörlüğü', max_length=150, verbose_name='Sorumlu Birim')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/', verbose_name='Dosya')),
                ('file_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harici Dosya Bağlantısı (İsteğe Bağlı)')),
                ('revision_number', models.CharField(default='Rev. 00', max_length=20, verbose_name='Revizyon No')),
                ('revision_date', models.DateField(auto_now=True, verbose_name='Son Revizyon Tarihi')),
                ('download_count', models.IntegerField(default=0, verbose_name='İndirme Sayısı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documentcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Doküman',
                'verbose_name_plural': 'Dokümanlar',
                'ordering': ['-download_count', '-created_at'],
            },
        ),
    ]
