# Generated by Django 4.2.23 on 2026-07-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Örn: DİF.2026.001', max_length=50, unique=True, verbose_name='DİF Numarası')),
                ('title', models.CharField(max_length=255, verbose_name='Uygunsuzluk / Gelişme Alanı Başlığı')),
                ('unit', models.CharField(default='Avrasya Üniversitesi Genel', max_length=150, verbose_name='Sorumlu Birim')),
                ('finding_type', models.CharField(choices=[('iç_tetkik', 'İç Kalite Tetkiki'), ('dış_tetkik', 'YÖKAK / Dış Değerlendirme'), ('paydaş', 'Paydaş Geri Bildirimi'), ('risk', 'Kurumsal Risk Değerlendirmesi')], default='iç_tetkik', max_length=30, verbose_name='Tespit Kaynağı')),
                ('root_cause', models.TextField(verbose_name='Kök Neden Analizi')),
                ('action_plan', models.TextField(verbose_name='Planlanan Düzeltici / Önleyici Faaliyetler')),
                ('responsible_person', models.CharField(max_length=150, verbose_name='Faaliyet Sorumlusu')),
                ('target_date', models.DateField(verbose_name='Hedef Kapatma Tarihi')),
                ('status', models.CharField(choices=[('acik', 'Açık / İşlem Bekliyor'), ('devam', 'Düzeltici Faaliyet Devam Ediyor'), ('dogrulama', 'Etkinlik Doğrulama Aşamasında'), ('kapali', 'Başarıyla Kapatıldı')], default='acik', max_length=20, verbose_name='DİF Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Açılış Tarihi')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Kapanış Tarihi')),
            ],
            options={
                'verbose_name': 'DİF Kaydı',
                'verbose_name_plural': 'DİF Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
